---
language: rust

env:
  global:
    - RUST_BACKTRACE: full

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    # Nightly channel
    - os: linux
      rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu
    - os: linux
      rust: nightly
      env: TARGET=x86_64-unknown-linux-musl
    - os: osx
      rust: nightly
      env: TARGET=x86_64-apple-darwin
    - os: windows
      rust: nightly
      env: TARGET=x86_64-pc-windows-msvc

      # Beta channel
    - os: linux
      rust: beta
      env: TARGET=x86_64-unknown-linux-gnu
    - os: linux
      rust: beta
      env: TARGET=x86_64-unknown-linux-musl
    - os: osx
      rust: beta
      env: TARGET=x86_64-apple-darwin
    - os: windows
      rust: beta
      env: TARGET=x86_64-pc-windows-msvc

      # Stable channel
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-musl
    - os: osx
      rust: stable
      env: TARGET=x86_64-apple-darwin
    - os: windows
      rust: stable
      env: TARGET=x86_64-pc-windows-msvc

cache: cargo

install: ci/install.sh
script: ci/script.sh
before_deploy: ci/before_deploy.sh
deploy:
  - provider: cargo
    skip_cleanup: true
    token:
      secure: "nUVqPH3nfQiU63jpZbb9VTgwAj5pBXdYXFUVqvboXc3hI+r7GYfpn1O2fqnYQZrkBHC07MaZ49CeJlpiXJ8R2Lyfe5+CxQOC1IBi/x38CTxMKZ8LSYN9XW7nY1i5+i99s7Ii5IXbsE0LBC0qArTOOOPm5IHauEeSvE8/KgMzHDp5GIGus77Z/iZek4v/SllUIF9NDK9pHtlQwpGIdQR8qle6BBj4Lx1ir5WwzzekwP4N1PEPs5snHj053V5VglxYpPPAjC+jbbpePN10NXiNDoPng30KTRqVuoQwyeQ4tlhxXV5f10hA//mqdja1CaVcj3IO3Lh+/FiRMN8xwCGgpuTnAOXEFiMoETVB6eqUv1k67I0c75BnS30pNcYMpi+zzj4u76IHeu+czD8LXM67C94DbCozziYTl9lVvBWKBRdLRLXRT+Z7D5qZVW27ItJuo4wnaxsNaL2+PWrKZU0/amz/vTRCZs0CBVXq92fLQTc8fG5Ffu6afR783drqVFYlkXqa+S9xzxDKADkCVZAIHjqwIojzDVSckZ4xiLgta4EzbkXQw07i9+j+8ipp0VxRodBzgWcM5/QntaDSxi1HH8reMkvrqxrT/yKyXUxxNwVXH/yZTefhR6mpUxw9JKPa2mljlpo783qaPe+0hSAwbsrGDhNemhx0KKABdlIkWS4="
    on:
      condition: '"$TARGET" = x86_64-unknown-linux-gnu'
      repo: mattmahn/gitall.rs
      rust: stable
      tags: true

  - provider: releases
    api_key:
      secure: "Vwtyoy12oNRCKv1FAkHOle8UXWfWlFckf341Scfp0KTMnpw3kdzkeGGXeNcXK+quT/BW3wGuqEd6K1bBA8uZy05QJ0seBLu2Lc+K0uGeUOmw7hjVw/mUlLaLf6QPgz5GQn5xVJP8e6Yms9QIA9NwVBAuMJm9RQwZdsWpfjsb1yPj2hp8pUnNyUReGVbphUtchM43ERoRxySd4ym6j3ceYYyTZ50B1l22aijWRgPxqTzvSan+CwZt7jkIYIVCdqI1IKwUTrvVwYOZV9r9btqQNqfrcXv1qE+naCOmrm8ZT93MD5w1yTXxrX6M4u/hpzxKeHjAHRoHz4J1OE9ul5UIYWn4PTpZQSPLIAdpPK7sr/1NgH5uHmFDQTR9Sj+BG3tinHWVJLqq8V/Czl35r/gPLFqrN++8BqdG17K6Us6RYZD8CICemlrybLF+sAQPOykNE4gnHTs+qK9N9KWXwiKX25Ue7fHs4nVf5S4+sDGSacC71YUJOrtCBK836Z77bNePms07m/Vqv/P2bjlLVqC+/Nl/VgR9YXHCMSHFQfgVxtO+GEzyPrBgVuhBeMldvbesXRmVOoxb/MveTiaU8k4dZTLfpKFDh4Vitsjs1MLu2Dqd8ZMiJL/k2GmkvIrTe0ryClz4dpy0r1jJz0zaM1sCBlvI99vGCFJlV/wh639bxLA="
    skip_cleanup: true
    file_glob: true
    file:
      - deployment/gitall-${TRAVIS_TAG}-${TARGET}.*
      - ${TRAVIS_BUILD_DIR}/deployment/gitall-${TRAVIS_TAG}-${TARGET}.*
    on:
      repo: mattmahn/gitall.rs
      rust: stable
      tags: true

notifications:
  email:
    on_success: never
